"""
Locations.py - location table.
"""

BASE_ID = 3874000
LOCATION_ID_OFFSET = 10000

location_table: dict[str, int] = {
    'Catch Bunger': BASE_ID + LOCATION_ID_OFFSET + 0,
    'Catch Fryder': BASE_ID + LOCATION_ID_OFFSET + 1,
    'Catch Shishkabug': BASE_ID + LOCATION_ID_OFFSET + 2,
    'Catch Sweetiefly': BASE_ID + LOCATION_ID_OFFSET + 3,
    'Catch White Strabby': BASE_ID + LOCATION_ID_OFFSET + 4,
    'Catch Dr. Sodie': BASE_ID + LOCATION_ID_OFFSET + 5,
    'Catch Weenyworm': BASE_ID + LOCATION_ID_OFFSET + 6,
    'Catch Cobhopper': BASE_ID + LOCATION_ID_OFFSET + 7,
    'Catch Crispy Snakpod': BASE_ID + LOCATION_ID_OFFSET + 8,
    'Catch Kweeble': BASE_ID + LOCATION_ID_OFFSET + 9,
    'Catch Crapple': BASE_ID + LOCATION_ID_OFFSET + 10,
    'Catch Orange Peelbug': BASE_ID + LOCATION_ID_OFFSET + 11,
    'Catch Razzby': BASE_ID + LOCATION_ID_OFFSET + 12,
    'Catch Green Grapeskeeto': BASE_ID + LOCATION_ID_OFFSET + 13,
    'Catch Snaquiri': BASE_ID + LOCATION_ID_OFFSET + 14,
    'Catch Tropicabug': BASE_ID + LOCATION_ID_OFFSET + 15,
    'Catch Lovely Sweetiefly': BASE_ID + LOCATION_ID_OFFSET + 16,
    'Catch Baja Tacroach': BASE_ID + LOCATION_ID_OFFSET + 17,
    'Catch Waffstackarak': BASE_ID + LOCATION_ID_OFFSET + 18,
    'Catch Grumpy Snakpod': BASE_ID + LOCATION_ID_OFFSET + 19,
    'Catch BBQ Bunger': BASE_ID + LOCATION_ID_OFFSET + 20,
    'Catch Sweet Fryder': BASE_ID + LOCATION_ID_OFFSET + 21,
    'Catch Ribblepede': BASE_ID + LOCATION_ID_OFFSET + 22,
    'Catch Poptick': BASE_ID + LOCATION_ID_OFFSET + 23,
    'Catch Spuddy': BASE_ID + LOCATION_ID_OFFSET + 24,
    'Catch Scorpenyo': BASE_ID + LOCATION_ID_OFFSET + 25,
    'Catch Shy Weenyworm': BASE_ID + LOCATION_ID_OFFSET + 26,
    'Catch Cheepoof': BASE_ID + LOCATION_ID_OFFSET + 27,
    'Catch White Cheepoof': BASE_ID + LOCATION_ID_OFFSET + 28,
    'Catch Crystal Sweetiefly': BASE_ID + LOCATION_ID_OFFSET + 29,
    'Catch Green Peelbug': BASE_ID + LOCATION_ID_OFFSET + 30,
    'Catch Puffy Snakpod': BASE_ID + LOCATION_ID_OFFSET + 31,
    'Catch Kwookie': BASE_ID + LOCATION_ID_OFFSET + 32,
    'Catch Charmallow': BASE_ID + LOCATION_ID_OFFSET + 33,
    'Catch Cinnasnail': BASE_ID + LOCATION_ID_OFFSET + 34,
    'Catch Sprinklepede': BASE_ID + LOCATION_ID_OFFSET + 35,
    'Catch Yellow Peelbug': BASE_ID + LOCATION_ID_OFFSET + 36,
    'Catch Bopsicle': BASE_ID + LOCATION_ID_OFFSET + 37,
    'Catch Big Bopsicle': BASE_ID + LOCATION_ID_OFFSET + 38,
    'Catch Rainbow Sweetiefly': BASE_ID + LOCATION_ID_OFFSET + 39,
    'Catch Nutty Snakpod': BASE_ID + LOCATION_ID_OFFSET + 40,
    'Catch All Inner Bugs!': BASE_ID + LOCATION_ID_OFFSET + 41,
    'Complete the Final Mission': BASE_ID + LOCATION_ID_OFFSET + 42,
    'Bugsnax File Complete': BASE_ID + LOCATION_ID_OFFSET + 43,
    'Catch Strabby': BASE_ID + LOCATION_ID_OFFSET + 44,
    'Catch Rootle': BASE_ID + LOCATION_ID_OFFSET + 45,
    'Collect Snak Trap': BASE_ID + LOCATION_ID_OFFSET + 46,
    'Collect Sauce Slinger': BASE_ID + LOCATION_ID_OFFSET + 47,
    'Collect Buggy Ball': BASE_ID + LOCATION_ID_OFFSET + 48,
    'Collect SnakGrappler': BASE_ID + LOCATION_ID_OFFSET + 49,
    'Collect Lunchpad': BASE_ID + LOCATION_ID_OFFSET + 50,
    'Catch White Rootle': BASE_ID + LOCATION_ID_OFFSET + 51,
    'Catch Twisty Snakpod': BASE_ID + LOCATION_ID_OFFSET + 52,
    'Catch Sub Sandopede': BASE_ID + LOCATION_ID_OFFSET + 53,
    'Catch Sandopede': BASE_ID + LOCATION_ID_OFFSET + 54,
    'Catch Pinkle': BASE_ID + LOCATION_ID_OFFSET + 55,
    'Catch Caramel Poptick': BASE_ID + LOCATION_ID_OFFSET + 56,
    'Catch Inchwrap': BASE_ID + LOCATION_ID_OFFSET + 57,
    'Catch Green Lollive': BASE_ID + LOCATION_ID_OFFSET + 58,
    'Catch Ruby Peelbug': BASE_ID + LOCATION_ID_OFFSET + 59,
    'Catch Hunnabee': BASE_ID + LOCATION_ID_OFFSET + 60,
    'Catch Red Banopper': BASE_ID + LOCATION_ID_OFFSET + 61,
    'Catch Green Crapple': BASE_ID + LOCATION_ID_OFFSET + 62,
    'Catch Grapeskeeto': BASE_ID + LOCATION_ID_OFFSET + 63,
    'Catch Golden Kweeble': BASE_ID + LOCATION_ID_OFFSET + 64,
    'Catch Lesser Cocomite': BASE_ID + LOCATION_ID_OFFSET + 65,
    'Catch Greater Cocomite': BASE_ID + LOCATION_ID_OFFSET + 66,
    'Catch La Sodieux': BASE_ID + LOCATION_ID_OFFSET + 67,
    'Catch Noodler': BASE_ID + LOCATION_ID_OFFSET + 68,
    'Catch Paletoss': BASE_ID + LOCATION_ID_OFFSET + 69,
    'Catch Paletoss Grande': BASE_ID + LOCATION_ID_OFFSET + 70,
    "Catch Flamin' Cheepoof": BASE_ID + LOCATION_ID_OFFSET + 71,
    'Catch Sherbie': BASE_ID + LOCATION_ID_OFFSET + 72,
    'Catch Fruity Snakpod': BASE_ID + LOCATION_ID_OFFSET + 73,
    'Catch Loaded Spuddy': BASE_ID + LOCATION_ID_OFFSET + 74,
    'Catch Tacroach': BASE_ID + LOCATION_ID_OFFSET + 75,
    'Catch Preying Picantis': BASE_ID + LOCATION_ID_OFFSET + 76,
    'Catch Black Lollive': BASE_ID + LOCATION_ID_OFFSET + 77,
    'Catch Buffalocust': BASE_ID + LOCATION_ID_OFFSET + 78,
    'Catch Eggler': BASE_ID + LOCATION_ID_OFFSET + 79,
    'Catch Flapjackarak': BASE_ID + LOCATION_ID_OFFSET + 80,
    'Catch Scorpepper': BASE_ID + LOCATION_ID_OFFSET + 81,
    'Catch Incherrito': BASE_ID + LOCATION_ID_OFFSET + 82,
    'Catch Black Razzby': BASE_ID + LOCATION_ID_OFFSET + 83,
    'Catch Sodie D': BASE_ID + LOCATION_ID_OFFSET + 84,
    'Catch Cheezer': BASE_ID + LOCATION_ID_OFFSET + 85,
    'Catch Meaty Snakpod': BASE_ID + LOCATION_ID_OFFSET + 86,
    'Catch Chippie': BASE_ID + LOCATION_ID_OFFSET + 87,
    'Catch Chillynilly': BASE_ID + LOCATION_ID_OFFSET + 88,
    'Catch Flutterjam': BASE_ID + LOCATION_ID_OFFSET + 89,
    'Catch Mt Sodie': BASE_ID + LOCATION_ID_OFFSET + 90,
    'Catch Stewdler': BASE_ID + LOCATION_ID_OFFSET + 91,
    'Catch Aggroll': BASE_ID + LOCATION_ID_OFFSET + 92,
    'Catch Banopper': BASE_ID + LOCATION_ID_OFFSET + 93,
    'Catch Scoopy': BASE_ID + LOCATION_ID_OFFSET + 94,
    'Catch Cheery': BASE_ID + LOCATION_ID_OFFSET + 95,
    'Catch Scoopy Banoopy': BASE_ID + LOCATION_ID_OFFSET + 96,
    'Catch Instabug': BASE_ID + LOCATION_ID_OFFSET + 97,
    'Catch Melty Snakpod': BASE_ID + LOCATION_ID_OFFSET + 98,
    'Gone Home!': BASE_ID + LOCATION_ID_OFFSET + 99,
    'Wambus Goes to Seed': BASE_ID + LOCATION_ID_OFFSET + 100,
    'Mystery Grumpus!': BASE_ID + LOCATION_ID_OFFSET + 101,
    'Beffica Gets Bored': BASE_ID + LOCATION_ID_OFFSET + 102,
    'Gramble Loses Sleep': BASE_ID + LOCATION_ID_OFFSET + 103,
    "Filbo's Cold Welcome": BASE_ID + LOCATION_ID_OFFSET + 104,
    'Triffany Bones up': BASE_ID + LOCATION_ID_OFFSET + 105,
    'Mail Time!': BASE_ID + LOCATION_ID_OFFSET + 106,
    'Wiggle Rocks The Beach': BASE_ID + LOCATION_ID_OFFSET + 107,
    'Snaxburg Gets Spooked': BASE_ID + LOCATION_ID_OFFSET + 108,
    'Get Hooked': BASE_ID + LOCATION_ID_OFFSET + 109,
    'Cromdo Cashes In': BASE_ID + LOCATION_ID_OFFSET + 110,
    'Snorpy Goes Outside': BASE_ID + LOCATION_ID_OFFSET + 111,
    'Chandlo Lives Large': BASE_ID + LOCATION_ID_OFFSET + 112,
    "Snaxburg Isn't Safe": BASE_ID + LOCATION_ID_OFFSET + 113,
    'Floofty Changes Everything': BASE_ID + LOCATION_ID_OFFSET + 114,
    'Shelda Speaks in Riddles': BASE_ID + LOCATION_ID_OFFSET + 115,
    'Eggabell Keeps Her Cool': BASE_ID + LOCATION_ID_OFFSET + 116,
    'Catch Pineantula': BASE_ID + LOCATION_ID_OFFSET + 117,
}
