"""
Rules.py - Logic rules for the apworld.
"""

location_rules = {
    'Catch Bunger': lambda state, player: state.has('Sauce Slinger', player),
    'Catch Fryder': lambda state, player: state.has('Sauce Slinger', player),
    'Catch Shishkabug': lambda state, player: state.has('Sauce Slinger', player),
    'Catch Sweetiefly': lambda state, player: state.has('Sauce Slinger', player),
    'Catch White Strabby': lambda state, player: state.has('Sauce Slinger', player),
    'Catch Dr. Sodie': lambda state, player: state.has('Sauce Slinger', player),
    'Catch Weenyworm': lambda state, player: state.has('Sauce Slinger', player),
    'Catch Cobhopper': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player),
    'Catch Crispy Snakpod': lambda state, player: state.has('Sauce Slinger', player),
    'Catch Kweeble': lambda state, player: state.has('Sauce Slinger', player),
    'Catch Crapple': lambda state, player: state.has('Sauce Slinger', player),
    'Catch Orange Peelbug': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player),
    'Catch Razzby': lambda state, player: state.has('Sauce Slinger', player),
    'Catch Green Grapeskeeto': lambda state, player: state.has('Sauce Slinger', player),
    'Catch Snaquiri': lambda state, player: state.has('Sauce Slinger', player),
    'Catch Tropicabug': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player),
    'Catch Lovely Sweetiefly': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player),
    'Catch Baja Tacroach': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player),
    'Catch Waffstackarak': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player),
    'Catch Grumpy Snakpod': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player),
    'Catch BBQ Bunger': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player),
    'Catch Sweet Fryder': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player),
    'Catch Ribblepede': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player),
    'Catch Poptick': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player),
    'Catch Spuddy': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player),
    'Catch Scorpenyo': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player),
    'Catch Shy Weenyworm': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player),
    'Catch Cheepoof': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player),
    'Catch White Cheepoof': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player),
    'Catch Crystal Sweetiefly': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Lunchpad', player),
    'Catch Green Peelbug': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player),
    'Catch Puffy Snakpod': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Lunchpad', player),
    'Catch Kwookie': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player),
    'Catch Charmallow': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player),
    'Catch Cinnasnail': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player),
    'Catch Sprinklepede': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player),
    'Catch Yellow Peelbug': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player),
    'Catch Bopsicle': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player),
    'Catch Big Bopsicle': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player),
    'Catch Rainbow Sweetiefly': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player) and state.has('Lunchpad', player),
    'Catch Nutty Snakpod': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player),
    'Catch All Inner Bugs!': lambda state, player: state.has_all({'Sauce Slinger', 'Buggy Ball', 'Lunchpad', 'SnakGrappler', 'Trip Shot'}, player),
    'Complete the Final Mission': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player) and state.has('Lunchpad', player),
    'Bugsnax File Complete': lambda state, player: state.has('Story Complete Token', player),
    'Catch Strabby': lambda state, player: True,
    'Catch Rootle': lambda state, player: True,
    'Collect Snak Trap': lambda state, player: True,
    'Collect Sauce Slinger': lambda state, player: True,
    'Collect Buggy Ball': lambda state, player: state.has('Sauce Slinger', player),
    'Collect SnakGrappler': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player),
    'Collect Lunchpad': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player),
    'Catch White Rootle': lambda state, player: state.has('Sauce Slinger', player),
    'Catch Twisty Snakpod': lambda state, player: state.has('Sauce Slinger', player),
    'Catch Sub Sandopede': lambda state, player: state.has('Sauce Slinger', player),
    'Catch Sandopede': lambda state, player: state.has('Sauce Slinger', player),
    'Catch Pinkle': lambda state, player: state.has('Sauce Slinger', player),
    'Catch Caramel Poptick': lambda state, player: state.has('Sauce Slinger', player),
    'Catch Inchwrap': lambda state, player: state.has('Sauce Slinger', player),
    'Catch Green Lollive': lambda state, player: state.has('Sauce Slinger', player),
    'Catch Ruby Peelbug': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player),
    'Catch Hunnabee': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player),
    'Catch Red Banopper': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player) and state.has('Lunchpad', player),
    'Catch Green Crapple': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player) and state.has('Lunchpad', player),
    'Catch Grapeskeeto': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player) and state.has('Lunchpad', player),
    'Catch Golden Kweeble': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player) and state.has('Lunchpad', player),
    'Catch Lesser Cocomite': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player) and state.has('Lunchpad', player),
    'Catch Greater Cocomite': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player) and state.has('Lunchpad', player),
    'Catch La Sodieux': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player) and state.has('Lunchpad', player),
    'Catch Noodler': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player) and state.has('Lunchpad', player),
    'Catch Paletoss': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player) and state.has('Lunchpad', player),
    'Catch Paletoss Grande': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player) and state.has('Lunchpad', player),
    "Catch Flamin' Cheepoof": lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player) and state.has('Lunchpad', player),
    'Catch Sherbie': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player) and state.has('Lunchpad', player),
    'Catch Fruity Snakpod': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player) and state.has('Lunchpad', player),
    'Catch Loaded Spuddy': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player) and state.has('Lunchpad', player),
    'Catch Tacroach': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player) and state.has('Lunchpad', player),
    'Catch Preying Picantis': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player) and state.has('Lunchpad', player),
    'Catch Black Lollive': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player) and state.has('Lunchpad', player),
    'Catch Buffalocust': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player) and state.has('Lunchpad', player),
    'Catch Eggler': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player) and state.has('Lunchpad', player),
    'Catch Flapjackarak': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player) and state.has('Lunchpad', player),
    'Catch Scorpepper': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player) and state.has('Lunchpad', player),
    'Catch Incherrito': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player) and state.has('Lunchpad', player),
    'Catch Black Razzby': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player) and state.has('Lunchpad', player),
    'Catch Sodie D': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player) and state.has('Lunchpad', player),
    'Catch Cheezer': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player) and state.has('Lunchpad', player),
    'Catch Meaty Snakpod': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player) and state.has('Lunchpad', player),
    'Catch Chippie': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player) and state.has('Lunchpad', player),
    'Catch Chillynilly': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player) and state.has('Lunchpad', player),
    'Catch Flutterjam': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player) and state.has('Lunchpad', player),
    'Catch Mt Sodie': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player) and state.has('Lunchpad', player),
    'Catch Stewdler': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player) and state.has('Lunchpad', player),
    'Catch Aggroll': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player) and state.has('Lunchpad', player),
    'Catch Banopper': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player) and state.has('Lunchpad', player),
    'Catch Scoopy': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player) and state.has('Lunchpad', player),
    'Catch Cheery': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player) and state.has('Lunchpad', player),
    'Catch Scoopy Banoopy': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player) and state.has('Lunchpad', player),
    'Catch Instabug': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player) and state.has('Lunchpad', player),
    'Catch Melty Snakpod': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player) and state.has('Lunchpad', player),
    'Gone Home!': lambda state, player: state.has('Sauce Slinger', player),
    'Wambus Goes to Seed': lambda state, player: state.has('Sauce Slinger', player),
    'Mystery Grumpus!': lambda state, player: state.has('Sauce Slinger', player),
    'Beffica Gets Bored': lambda state, player: state.has('Sauce Slinger', player),
    'Gramble Loses Sleep': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player),
    "Filbo's Cold Welcome": lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player),
    'Triffany Bones up': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player),
    'Mail Time!': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player),
    'Wiggle Rocks The Beach': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player),
    'Snaxburg Gets Spooked': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player),
    'Get Hooked': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player),
    'Cromdo Cashes In': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Lunchpad', player),
    'Snorpy Goes Outside': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player),
    'Chandlo Lives Large': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player),
    "Snaxburg Isn't Safe": lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player) and state.has('Lunchpad', player),
    'Floofty Changes Everything': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player) and state.has('Lunchpad', player),
    'Shelda Speaks in Riddles': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player) and state.has('Lunchpad', player),
    'Eggabell Keeps Her Cool': lambda state, player: state.has('Sauce Slinger', player) and state.has('Buggy Ball', player) and state.has('Trip Shot', player) and state.has('SnakGrappler', player) and state.has('Lunchpad', player),
    'Catch Pineantula': lambda state, player: state.has('Sauce Slinger', player),
}
